services:
  - type: web
    name: pycord
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: MONGODB_DB_NAME
        value: pycord
      - key: CLERK_SECRET_KEY
        sync: false
      - key: CLERK_WEBHOOK_SECRET
        sync: false
      - key: SKIP_WEBHOOK_VERIFICATION
        value: "true"
      - key: VITE_CLERK_PUBLISHABLE_KEY
        sync: false
